<a href="https://www.kaggle.com/lucifierx/nlp-for-beginners?scriptVersionId=90444716" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/d/lucifierx/spamhamclassifier/SpamClassifier.csv


<h1 style= "text-align: center"> NLP </h1>

**NLP stands for Natural Language Processing, which is a part of Computer Science, Human language, and Artificial Intelligence. It is the technology that is used by machines to understand, analyse, manipulate, and interpret human's languages.**
**Applications of NLP**
1. Question Answering
2. Spam Detection
3. Sentiment Analysis
4. Chatbot
5. Machine Translation

<h1 style= "text-align: center"> Tokenization </h1>

In [2]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords


In [3]:

paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               """

In [4]:
sentences = nltk.sent_tokenize(paragraph)
stemmer= PorterStemmer()

In [5]:
#stemming
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=' '.join(words)
    print(sentences)

['I three vision india .', 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.', 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.', 'Yet we have not done this to any other nation.', 'We have not conquered anyone.', 'We have not grabbed their land, their culture, \n               their history and tried to enforce our way of life on them.']
['I three vision india .', 'In 3000 year histori , peopl world come invad us , captur land , conquer mind .', 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.', 'Yet we have not done this to any other nation.', 'We have not conquered anyone.', 'We have not grabbed their land, their culture, 

<h1 style= "text-align: center"> Lemmatization </h1>

In [6]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

paragraphs = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. """


In [7]:
sentences = nltk.sent_tokenize(paragraphs)
lemmatizer = WordNetLemmatizer()

#Lemmatization 
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words("english"))]
    sentences[i]=' '.join(words)
    print(sentences)
    


['I three vision India .', 'In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds.', 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.', 'Yet we have not done this to any other nation.', 'We have not conquered anyone.', 'We have not grabbed their land, their culture, \n               their history and tried to enforce our way of life on them.']
['I three vision India .', 'In 3000 year history , people world come invaded u , captured land , conquered mind .', 'From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours.', 'Yet we have not done this to any other nation.', 'We have not conquered anyone.', 'We have not grabbed their land, their cul

<h1 style= "text-align: center"> Bag of words </h1>

In [8]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. """

In [9]:
import re
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
ps = PorterStemmer()
wordnet=WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
    
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
print(X)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0]
 [1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0]]


<h1 style= "text-align: center"> TFIDF </h1>

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
output = tfidf.fit_transform(corpus).toarray()
print(output)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.57735027 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.57735027 0.         0.         0.
  0.         0.57735027 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.32125136 0.32125136
  0.26343071 0.         0.         0.         0.         0.
  0.         0.         0.26343071 0.         0.32125136 0.26343071
  0.         0.         0.32125136 0.         0.         0.
  0.32125136 0.         0.         0.         0.         0.
  0.26343071 0.         0.         0.32125136 0.32125136 0.        ]
 [0.28091192 0.         0.28091192 0.28091192 0.         0.
  0.         0.         0.         0.28091192 0.         0.28091192
  0.         0.28091192 0.         0.         0.         0.
  0.         0.28091192 0.         0.28091192 0.         0

<h1 style= "text-align: center">  Spam Classifier </h1>

In [11]:
messages=pd.read_csv("../input/d/lucifierx/spamhamclassifier/SpamClassifier.csv", names=['label','message'])
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus =[]
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
y = pd.get_dummies(messages['label'])
y = y.iloc[:,-1].values

# Train-Test-Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state=0)

# Train Model using Naive Bayes
from sklearn.naive_bayes import MultinomialNB
my_model = MultinomialNB().fit(x_train, y_train)
y_pred = my_model.predict(x_test)

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
y_pred

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [14]:
# msg = input("Enter Message: ")
# msgInput = cv.transform([msg])
# predict = my_model.predict(msgInput)
# if(predict[0]==0):
#     print("------------------------MESSAGE-SENT-[CHECK-SPAM-FOLDER]---------------------------")
# else:
#     print("---------------------------MESSAGE-SENT-[CHECK-INBOX]------------------------------")

<h1> Word2vec </h1>


In [15]:
from gensim.models import Word2Vec

text = re.sub(r'\[[0-9]*\]',' ',paragraph)
text = re.sub(r'\s+',' ',text)
text = text.lower()
text = re.sub(r'\d',' ',text)
text = re.sub(r'\s+',' ',text)

sentences = nltk.sent_tokenize(text)

sentences = [nltk.word_tokenize(sentence) for sentence in sentences]

for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]
    
model = Word2Vec(sentences, min_count=1)
words= model.wv.key_to_index

vector = model.wv['visions']

similar = model.wv.most_similar('three')
print(vector)
print('____'*20)
print(similar)


[ 0.00180023  0.00704609  0.0029447  -0.00698085  0.00771268 -0.00598893
  0.00899771  0.0029592  -0.00401529 -0.00468899 -0.00441672 -0.00614646
  0.00937874 -0.0026496   0.00777244 -0.00968034  0.00210879 -0.00123362
  0.00754423 -0.0090546   0.00743756 -0.0051058  -0.00601377 -0.00564916
 -0.00337917 -0.0034111  -0.00319566 -0.0074922   0.00070878 -0.00057607
 -0.001684    0.00375713 -0.00762019 -0.00322142  0.00515534  0.00854386
 -0.00980994  0.00719534  0.00530949 -0.0038797   0.00857616 -0.00922199
  0.00724868  0.00536383  0.00129359 -0.00519975 -0.00417865 -0.00335678
  0.00160829  0.0015867   0.00738824  0.00997759  0.00886734 -0.00400645
  0.00964539 -0.00062954  0.00486543  0.00254902 -0.00062981  0.00366745
 -0.00531941 -0.00575668 -0.00760464  0.00190643  0.00652587  0.00088213
  0.00125695  0.0031716   0.00813467 -0.00770006  0.00226075 -0.00747411
  0.00370981  0.00951055  0.00752026  0.00642603  0.00801477  0.00655114
  0.00685668  0.00868209 -0.00494804  0.00921295  0