In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Word Embedding

Word embeddings provide a dense representation of words and their relative meanings.

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Vocubulary Size 
voc_size=10000

In [6]:
# One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print(one_hot_repr)

[[9819, 9352, 9665, 5348], [9819, 9352, 9665, 4164], [9819, 5405, 9665, 3282], [742, 3933, 8818, 1886, 354], [742, 3933, 8818, 1886, 7592], [876, 9819, 8090, 9665, 5427], [8880, 9162, 567, 1886]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9819 9352 9665 5348]
 [   0    0    0    0 9819 9352 9665 4164]
 [   0    0    0    0 9819 5405 9665 3282]
 [   0    0    0  742 3933 8818 1886  354]
 [   0    0    0  742 3933 8818 1886 7592]
 [   0    0    0  876 9819 8090 9665 5427]
 [   0    0    0    0 8880 9162  567 1886]]


In [9]:
#  dim is features how many features you want
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length= sent_length))
model.compile('adam', 'mse')

2022-03-20 11:25:24.089592: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-2.3863209e-02  1.3696123e-02  3.6329851e-03 -9.9780075e-03
    3.7971210e-02 -8.2596764e-03 -2.0149006e-02 -4.5981970e-02
    3.2174516e-02  1.8855844e-02]
  [-2.3863209e-02  1.3696123e-02  3.6329851e-03 -9.9780075e-03
    3.7971210e-02 -8.2596764e-03 -2.0149006e-02 -4.5981970e-02
    3.2174516e-02  1.8855844e-02]
  [-2.3863209e-02  1.3696123e-02  3.6329851e-03 -9.9780075e-03
    3.7971210e-02 -8.2596764e-03 -2.0149006e-02 -4.5981970e-02
    3.2174516e-02  1.8855844e-02]
  [-2.3863209e-02  1.3696123e-02  3.6329851e-03 -9.9780075e-03
    3.7971210e-02 -8.2596764e-03 -2.0149006e-02 -4.5981970e-02
    3.2174516e-02  1.8855844e-02]
  [-4.7376044e-03  3.7641432e-02 -2.5686814e-02  3.0117657e-02
   -2.2092057e-02 -3.8116731e-02 -3.5958003e-02 -3.2760516e-02
   -4.9271356e-02  3.4584548e-02]
  [-2.9389059e-02 -3.0965209e-03  3.2413866e-02 -4.5937516e-02
    1.9609775e-02  4.0157761e-02  2.3216009e-04  4.1465942e-02
   -2.2555197e-02 -4.5378577e-02]
  [-2.3392260e-02  1.3969291e-02 -3.7197

2022-03-20 11:25:24.323378: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9819, 9352, 9665, 5348], dtype=int32)

In [14]:
print(model.predict(embedded_docs[0]))

[[[-0.02386321  0.01369612  0.00363299 -0.00997801  0.03797121
   -0.00825968 -0.02014901 -0.04598197  0.03217452  0.01885584]]

 [[-0.02386321  0.01369612  0.00363299 -0.00997801  0.03797121
   -0.00825968 -0.02014901 -0.04598197  0.03217452  0.01885584]]

 [[-0.02386321  0.01369612  0.00363299 -0.00997801  0.03797121
   -0.00825968 -0.02014901 -0.04598197  0.03217452  0.01885584]]

 [[-0.02386321  0.01369612  0.00363299 -0.00997801  0.03797121
   -0.00825968 -0.02014901 -0.04598197  0.03217452  0.01885584]]

 [[-0.0047376   0.03764143 -0.02568681  0.03011766 -0.02209206
   -0.03811673 -0.035958   -0.03276052 -0.04927136  0.03458455]]

 [[-0.02938906 -0.00309652  0.03241387 -0.04593752  0.01960978
    0.04015776  0.00023216  0.04146594 -0.0225552  -0.04537858]]

 [[-0.02339226  0.01396929 -0.03719751 -0.03012349 -0.01952047
    0.01669557  0.00836552  0.03400857 -0.03794343 -0.03361641]]

 [[ 0.03560784  0.04274488 -0.02035867 -0.00474249 -0.04766273
    0.02768116  0.02328608 -0.0251